#!/bin/bash
# Purpose: A script to set up Arch Linux for Neuroimaging
# Author: Liam Timms
# Date: 9/16/19
# Version: 0.1.1

# Download Canadian and USA mirrorlist, then rank them by speed
sudo pacman -S pacman-contrib
curl -s "https://www.archlinux.org/mirrorlist/?country=CA&country=US&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 10 -

sudo pacman -S pacutils
# Basic useful programs
# Utilities
sudo pacman -S xclip fzf zip unzip cmake
# CLI stuff
sudo pacman -S neofetch ranger neovim awesome-terminal-fonts
# GUI stuff
sudo pacman -S xf86-video-intel
sudo pacman -S xf86-input-synaptics
sudo pacman -S xorg
sudo pacman -S firefox noto-fonts jupyterlab zathura-pdf-mupdf baobab libreoffice-fresh
# Download Yay and install it from source code
# Yay will then be used to install all AUR packages
cd ~
mkdir .yay-setup
cd .yay-setup
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

# Now start installing AUR packages for Neuroimaging
yay -S python-nibabel
yay -S gdcm
# commenting out spm12 because it should be installed after MATLAB
# However, it's possible this is a hidden dependency for another
# Neuroimaging suite
# yay -S spm12
yay -S freesurfer
yay -S fsl
# yay -S ants
yay -S 3dslicer
yay -S afni
yay -S insight-toolkit #need to add patch: make generic in CMAKE
# Ants manual install
mkdir ~/code
cd code/
git clone https://github.com/stnava/ANTs.git
mkdir -p ~/bin/ants
cd ~/bin/ants/
ccmake ~/code/ANTs/
make
# At this point, the underlying Neuroimaging suites should be
# installed and working, but not those that depend on MATLAB
pacman -Qi ants
git clone https://github.com/liamtimms/aur.git

# Setting up GNOME
sudo pacman -S xorg
sudo pacman -S libinput
sudo pacman -S gnome gnome-terminal gnome-tweaks
sudo pacman -S gdm # the display manager
systemctl enable gdm
sudo pacman -S networkmanager gnome-keyring
sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager
sudo pacman -S gnome-shell-extensions
yay -S ttf-ms-fonts
# Themeing
sudo pacman -S hicolor-icon-theme papirus-icon-theme arc-gtk-theme
sudo pacman -S chrome-gnome-shell
yay -S gnome-terminal-transparency
yay -S gnome-shell-extension-dash-to-dock
sudo pacman -S nodejs

# MATLAB is very annoying and they don't let Linux repos
# host any of the files, it's the worst
# To install MATLAB you must:
# 1. go to mathworks site
# 2. you have to download, extract and start installer
# 3. when choosing the path, be sure to install it into /opt/MATLAB/<version name>
# matlab set up
xhost si:localuser:root
sudo pacman -S gtk-engine-murrine
cd /opt/MATLAB/R2019b/cefclient/sys/os/glnxa64
sudo mkdir exclude
sudo mv libg* exclude/
cd ~

yay -S spm12
# Add SPM12 to MATLAB path file initialized by freesurfer
cat <<EOT >> ~/matlab/startup.m
%------------------- SPM 12 --------------------------%
spmhome = '/opt/spm12';
if (exist(spmhome) == 7)
	path(path,spmhome);
end
clear spmhome
%-----------------------------------------------------%
EOT

yay -S python-nipype
yay --stats --show
