#!/bin/bash
# Purpose: A script to set up Arch Linux for Neuroimaging
# Author: Liam Timms
# Date: 9/16/19
# Version: 0.1.1

# Download Canadian and USA mirrorlist, then rank them by speed
sudo pacman --noconfirm --needed -S pacman-contrib
cp ~/etc/pacman.d/mirrorlist ~/etc/pacman.d/mirrorlist.backup
curl -s "https://www.archlinux.org/mirrorlist/?country=CA&country=US&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 10 - > ~/etc/pacman.d/mirrorlist
sudo pacman --noconfirm --needed -S base-devel

# Download Yay and install it from source code
# Yay will then be used to install all AUR packages
cd ~
#mkdir .yay-setup
#cd .yay-setup
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
# Save Sudo Loop option to stop sudo from timing out during builds
yay --save --sudoloop

# Basic useful programs
# Utilities
sudo pacman --noconfirm --needed -S pacutils xclip fzf zip unzip cmake
# CLI stuff
sudo pacman --noconfirm --needed -S neofetch ranger neovim python-pynvim awesome-terminal-fonts
# VirtualBox guest help
sudo pacman --noconfirm --needed -S virtualbox-guest-modules-arch virtualbox-guest-utils xf86-video-vmware
# GUI stuff
#sudo pacman --noconfirm --needed -S xf86-video-intel
sudo pacman --noconfirm --needed -S xorg
sudo pacman --noconfirm --needed -S xf86-input-synaptics
sudo pacman --noconfirm --needed -S firefox noto-fonts jupyterlab zathura-pdf-mupdf baobab libreoffice-fresh
# Python base packages
sudo pacman --noconfirm --needed -S python-scipy
# Now start installing AUR packages for Neuroimaging
yay -S python-nibabel
yay -S gdcm
# commenting out spm12 because it should be installed after MATLAB
# However, it's possible this is a hidden dependency for another
# Neuroimaging suite
# yay -S spm12
yay -S freesurfer
yay -S fsl
# yay -S ants
yay -S 3dslicer
yay -S afni
yay -S insight-toolkit #need to add patch: make generic in CMAKE


# Ants manual install
mkdir ~/code
cd ~/code/
git clone https://github.com/stnava/ANTs.git
mkdir -p ~/bin/ants
cd ~/bin/ants/
ccmake ~/code/ANTs/
make
cat <<EOT >> ~/.bashrc
export ANTSPATH=${HOME}/bin/ants/bin/
export PATH=${ANTSPATH}:$PATH
EOT
pacman -Qi ants
# At this point, the underlying Neuroimaging suites should be
# installed and working, but not those that depend on MATLAB

#git clone https://github.com/liamtimms/aur.git

# Setting up GNOME
sudo pacman --noconfirm --needed -S xorg
sudo pacman --noconfirm --needed -S libinput
sudo pacman --noconfirm --needed -S gnome gnome-terminal gnome-tweaks
sudo pacman --noconfirm --needed -S gdm # the display manager
systemctl enable gdm
sudo pacman --noconfirm --needed -S networkmanager gnome-keyring
sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager
sudo pacman --noconfirm --needed -S gnome-shell-extensions
yay -S ttf-ms-fonts
# Themeing
sudo pacman --noconfirm --needed -S hicolor-icon-theme papirus-icon-theme arc-gtk-theme
sudo pacman --noconfirm --needed -S chrome-gnome-shell
yay -S gnome-terminal-transparency
yay -S gnome-shell-extension-dash-to-dock
sudo pacman --noconfirm --needed -S nodejs

# Next you need to install MATLAB and then run MRArch2
