#!/bin/bash
# Purpose: A script to set up Arch Linux for Neuroimaging
# Author: Liam Timms
# Version: 0.3.0

# Download Canadian and USA mirrorlist, then rank them by speed
sudo pacman --noconfirm --needed -S reflector
cp ~/etc/pacman.d/mirrorlist ~/etc/pacman.d/mirrorlist.backup
reflector --latest 200 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
sudo pacman --noconfirm --needed -S pacman-contrib base-devel


# Download Yay and install it from source code
# Yay will then be used to install all AUR packages
cd ~
#mkdir .yay-setup
#cd .yay-setup
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
# Save Sudo Loop option to stop sudo from timing out during builds
yay --save --sudoloop
yay --save --nodiffmenu
yay --save --nocleanmenu
yay --save --cleanafter
yay --save --noremovemake


# Now start installing AUR packages for Neuroimaging
# For BART we need "openblas-lapack" which will means a different version of numpy is needed too
# yay -S openblas-lapack # called as a dependency by:
yay -S python-numpy-openblas
# installing this early so that numpy doesn't need to be overwriten later

# Basic useful programs
# Utilities
sudo pacman --noconfirm --needed -S pacutils xclip zip unzip cmake
# CLI stuff
sudo pacman --noconfirm --needed -S fzf neofetch ranger neovim python-pynvim awesome-terminal-fonts noto-fonts
# VirtualBox guest help
sudo pacman --noconfirm --needed -S virtualbox-guest-modules-arch virtualbox-guest-utils
# be sure you install the correct video driver
sudo pacman xf86-video-vmware
# GUI stuff
# sudo pacman --noconfirm --needed -S xf86-input-synaptics
sudo pacman --noconfirm --needed -S firefox jupyterlab zathura-pdf-mupdf
# Python packages
sudo pacman --noconfirm --needed -S python-scipy

# And now back to the yay
yay -S bart-git
yay -S python-nibabel
yay -S python-dcm2bids
yay -S gdcm
yay -S freesurfer
yay -S fsl
yay -S 3dslicer
yay -S afni
yay -S insight-toolkit #need to add patch: make generic in CMAKE
yay -S ants-git

## At this point, the most underlying Neuroimaging suites should be
## installed and working, but not those that depend on MATLAB


echo "IMPORTANT NOTE: Next you need to install MATLAB manually and then run MRArch2"
