#!/bin/bash
# Script to be run after installing MATLAB

# MATLAB is very annoying and they don't let Linux repos
# host any of the files, it's the worst
# To install MATLAB you must:
# 1. go to mathworks site
# 2. you have to download, extract and start installer
# 3. when choosing the path, be sure to install it into /opt/MATLAB/<version name>
# matlab set up
xhost si:localuser:root
sudo pacman -S gtk-engine-murrine
cd /opt/matlab/R2019b/cefclient/sys/os/glnxa64
sudo mkdir exclude
sudo mv libg* exclude/
cd ~

yay -S spm12
# Add SPM12 to MATLAB path file initialized by freesurfer
cat <<EOT >> ~/matlab/startup.m
%------------------- SPM 12 --------------------------%
spmhome = '/opt/spm12';
if (exist(spmhome) == 7)
	path(path,spmhome);
end
clear spmhome
%-----------------------------------------------------%
EOT

# To set-up nipype correctly we need to do a bit of shenanigans
# to work around this: https://github.com/nipy/nipype/issues/3055
yay -S python-prov
yay -S python-neurdflib # This should build but Error on install
cd ~/.cache/yay/python-neurdflib/
# Now we force the installation of neurdflib
# this line was broken by pacman update 5.2
# sudo pacman -U --force python-neurdflib*.pkg.tar.xz
sudo pacman -U python-neurdflib*.pkg.tar.xz --overwrite usr/lib/*

# An now we finally can install nipype
yay -S python-nipype
yay --gendb
yay --stats --show
