#!/bin/bash
# Purpose: A script to set up Arch Linux for Neuroimaging
# Author: Liam Timms
# Date: 9/16/19
# Version: 0.1.1

# Download Canadian and USA mirrorlist, then rank them by speed
sudo pacman -S pacman-contrib
curl -s "https://www.archlinux.org/mirrorlist/?country=CA&country=US&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 10 -

cd ~
#mkdir .yay-setup
#cd .yay-setup
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

sudo pacman -S pacutils
# Basic useful programs
# Utilities
sudo pacman -S xclip fzf zip unzip cmake
# CLI stuff
sudo pacman -S neofetch ranger neovim awesome-terminal-fonts
# GUI stuff
sudo pacman -S xf86-video-intel
sudo pacman -S xf86-input-synaptics
sudo pacman -S xorg
sudo pacman -S firefox noto-fonts jupyterlab zathura-pdf-mupdf baobab libreoffice-fresh
# Download Yay and install it from source code
# Yay will then be used to install all AUR packages
# Now start installing AUR packages for Neuroimaging
yay -S python-nibabel
yay -S gdcm
# commenting out spm12 because it should be installed after MATLAB
# However, it's possible this is a hidden dependency for another
# Neuroimaging suite
# yay -S spm12
yay -S freesurfer
yay -S fsl
# yay -S ants
yay -S 3dslicer
yay -S afni
yay -S insight-toolkit #need to add patch: make generic in CMAKE


# Ants manual install
cd ~
mkdir ~/code
cd ~/code/
git clone https://github.com/stnava/ANTs.git
mkdir -p ~/bin/ants
cd ~/bin/ants/
ccmake ~/code/ANTs/
make
# At this point, the underlying Neuroimaging suites should be
# installed and working, but not those that depend on MATLAB
pacman -Qi ants
cat <<EOT >> ~/.bashrc
export ANTSPATH=${HOME}/bin/ants/bin/
export PATH=${ANTSPATH}:$PATH
EOT

#git clone https://github.com/liamtimms/aur.git

# Setting up GNOME
sudo pacman -S xorg
sudo pacman -S libinput
sudo pacman -S gnome gnome-terminal gnome-tweaks
sudo pacman -S gdm # the display manager
systemctl enable gdm
sudo pacman -S networkmanager gnome-keyring
sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager
sudo pacman -S gnome-shell-extensions
yay -S ttf-ms-fonts
# Themeing
sudo pacman -S hicolor-icon-theme papirus-icon-theme arc-gtk-theme
sudo pacman -S chrome-gnome-shell
yay -S gnome-terminal-transparency
yay -S gnome-shell-extension-dash-to-dock
sudo pacman -S nodejs

# Next you need to install MATLAB and then run MRArch2
